package:
  name: fcl
  version: 0.4.0

source:
  fn: fcl-0.4.0.tar.gz
  url: https://github.com/flexible-collision-library/fcl/archive/0.4.0.tar.gz

build:
  detect_binary_files_with_prefix: True
  number: 5

requirements:
  build:
    - libccd
    - cmake
    - flann
    - gcc [linux]
    - octomap 1.7.2

  run:
    - libccd
    - flann
    - octomap 1.7.2

about:
  home: https://github.com/flexible-collision-library/fcl
  license: LGPL
