package:
  name: rapidjson
  version: v1.0.2

source:
  fn: v1.0.2.tar.gz
  url: https://github.com/miloyip/rapidjson/archive/v1.0.2.tar.gz

build:
  detect_binary_files_with_prefix: True
  number: 5

requirements:
  build:
    - cmake
    - gcc [linux]

about:
  home: https://github.com/miloyip/rapidjson
  license: LGPL
